[build]
  publish = "."
  functions = "netlify/functions"
  command = "echo 'No build command needed'"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stripe"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
